collections:
  csumb:
    output: true
    permalink: /csumb/:name/

  projects:
    output: true
    permalink: /projects/:name/

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

excerpt_separator: "<!--more-->"