# Trust Cloudflare IPs
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 131.0.72.0/22;
real_ip_header CF-Connecting-IP;

# HTTP Redirect to HTTPS
server {
    listen 80;
    server_name garygigabytes.com culinaryotter.com;
    return 301 https://$host$request_uri;
}

# ggbsite (HTTPS)
server {
    listen 443 ssl http2;
    server_name garygigabytes.com;

    ssl_certificate /etc/nginx/certs/garygigabytes.pem;
    ssl_certificate_key /etc/nginx/certs/garygigabytes.key;

    location / {
        proxy_pass http://ggsite:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# culinaryotter (HTTPS)
server {
    listen 443 ssl http2;
    server_name culinaryotter.com;

    ssl_certificate /etc/nginx/certs/culinaryotter.pem;
    ssl_certificate_key /etc/nginx/certs/culinaryotter.key;

    location / {
        proxy_pass http://culinaryotter:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
